from pathlib import Path

TICKER = "603799"
TICKER_NAME = "华友钴业"
DB_PATH = Path(__file__).parent / "huayou.db"

FETCH_RETRY_ATTEMPTS = 3
FETCH_RETRY_DELAYS = [5, 15, 45]

BACKTEST_MIN_OOS_TRADES = 20
BACKTEST_MIN_WIN_RATE = 0.55
BACKTEST_MIN_SHARPE = 1.0
BACKTEST_MAX_DRAWDOWN = 0.20

REGIME_MIN_SAMPLES = 15
REGIME_CONFIDENCE_CLAMP = (0.50, 0.85)
